version: '3.7'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - '3002:3002'
    networks:
      - service_net
    volumes:
      - ./:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
      - ./dist:/usr/src/app/dist
    depends_on:
      - db
    environment:
      NODE_ENV: development
      PORT: 3002
      POSTGRES_PASSWORD: dummypass
      POSTGRES_DB: dev-db
      POSTGRES_USER: jelkand
      POSTGRES_HOST: db
      JWT_TOKEN_KEY: development

  ci:
    build:
      context: .
      dockerfile: Dockerfile
    image: ilm-user-service
    ports:
      - '3002:3002'
    networks:
      - service_net
    volumes:
      - ./:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
      - /usr/src/app/dist
    environment:
      PORT: 3002
      NODE_ENV: production
      POSTGRES_PASSWORD: fnord
      POSTGRES_DB: fnord
      POSTGRES_USER: fnord
      JWT_TOKEN_KEY: fnord

  db:
    image: postgres:11.5-alpine
    networks:
      - service_net
    ports:
      - 5432
    environment:
      POSTGRES_PASSWORD: dummypass
      POSTGRES_DB: dev-db
      POSTGRES_USER: jelkand
    volumes:
      - /var/lib/postgresql/data

networks:
  service_net:
